In [2]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
C=np.array([[9,8],[7,6]])

In [3]:
A@B, B@A, A@(B+C), A@B + A@C

(array([[19, 22],
        [43, 50]]),
 array([[23, 34],
        [31, 46]]),
 array([[42, 42],
        [98, 98]]),
 array([[42, 42],
        [98, 98]]))

In [4]:
(A+B).T, A.T+B.T, (A@B).T, B.T @ A.T

(array([[ 6, 10],
        [ 8, 12]]),
 array([[ 6, 10],
        [ 8, 12]]),
 array([[19, 43],
        [22, 50]]),
 array([[19, 43],
        [22, 50]]))

In [33]:
from sklearn.datasets import load_iris
X=load_iris().data
(n,m)=X.shape
print((1/n)*(np.ones((n,1))@np.ones((n,1)).T@X))


[[5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 3.05733333 3.758      1.19933333]
 [5.84333333 

In [32]:
np.ones((n,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [2]:
#연습문제 2.2.6
A=np.array([1, 2])
B=np.array([[1, 2],[3,4]])
C=np.array([[5],[6]])

(A@B)@C,A@(B@C)

(array([95]), array([95]))