### 행렬놈

In [3]:
A = (np.arange(9) - 4).reshape((3,3))
np.linalg.norm(A)

7.745966692414834

### 대각합

In [4]:
np.trace(np.eye(3))

3.0

### 행렬식

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(A)

6.66133814775094e-16

### 역행렬

In [6]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1]])
Ainv = np.linalg.inv(A)
Ainv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

In [7]:
b = np.array([[2], [2], [3]])
x = Ainv @ b
x

array([[1.],
       [1.],
       [1.]])

In [8]:
A @ x - b

array([[0.],
       [0.],
       [0.]])

In [10]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

array([[1.],
       [1.],
       [1.]])

### 연습문제 2.4.5

In [11]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target
A = X[:4, [0, 4, 5, 6]] #'CRIM'. 'NOX', 'RM', 'AGE'
b = y[:4]

In [13]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01])

### 최소자승문제

In [14]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1], [1, 1, 2]])
b = np.array([[2], [2], [3], [4.1]])

In [17]:
Apinv = np.linalg.inv(A.T @ A) @ A.T
Apinv

array([[ 0.33333333, -1.        ,  0.33333333,  0.33333333],
       [ 0.5       ,  1.        ,  0.        , -0.5       ],
       [-0.5       ,  0.        ,  0.        ,  0.5       ]])

In [19]:
x = Apinv @ b
x

array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [20]:
A @ x

array([[1.98333333],
       [2.        ],
       [3.03333333],
       [4.08333333]])

In [21]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [22]:
resid, np.linalg.norm(A @ x - b) ** 2

(array([0.00166667]), 0.001666666666666655)

### 연습문제 2.4.6

In [23]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target
x, resid, rank, s = np.linalg.lstsq(X, y)
x

array([-9.28965170e-02,  4.87149552e-02, -4.05997958e-03,  2.85399882e+00,
       -2.86843637e+00,  5.92814778e+00, -7.26933458e-03, -9.68514157e-01,
        1.71151128e-01, -9.39621540e-03, -3.92190926e-01,  1.49056102e-02,
       -4.16304471e-01])