# 7.4 다변수 확률변수

### 연습문제 7.4.1

In [ ]:
1. 0.02
2. 0
3. (C,C)

### 연습문제 7.4.2

In [ ]:
1. 0.08
2. 0.18

### 연습문제 7.4.3

In [ ]:
1. B
2. C

### 연습문제 7.4.4

In [ ]:
1. (70, 170)
2. 70
3. 60

### 연습문제 7.5.1

In [2]:
from sklearn.datasets import load_iris
X = load_iris().data
x1 = X[:, 0]
x2 = X[:, 1]
x3 = X[:, 2]
x4 = X[:, 3]

1.

In [3]:
sp.stats.pearsonr(x1, x2)[0]

-0.11756978413300188

2.

In [4]:
sp.stats.pearsonr(x3, x4)[0]

0.9628654314027963

3.

In [5]:
sp.stats.pearsonr(x2, x4)[0]

-0.36612593253643866

### 연습문제 7.5.2

In [6]:
A = np.random.randint(1,100,10)
B = np.random.randint(1,100,10)
A, B

(array([52, 28, 14, 33, 74, 88, 67, 16, 22,  8]),
 array([85, 35, 26, 72, 29, 31, 64, 80, 47, 58]))

In [7]:
sp.stats.pearsonr(A, B)[0]

-0.1972345626940133

In [8]:
C = np.random.randint(1,100,10000)
D = np.random.randint(1,100,10000)

In [9]:
sp.stats.pearsonr(C, D)[0]

0.013733244066156638

선택된 표본이 우연한 상관관계를 가질 수 있기 때문이다.

### 연습문제 7.5.3

노트 작성

### 연습문제 7.5.4

In [31]:
n = np.size(X, 0)
m = 4
n1 = np.ones((n,1))
x_bar = (X.T @ n1) * (1/n)
X0 = X - (n1 @  x_bar.T)
S = (X0.T @ X0) *(1/n)
S

array([[ 0.68112222, -0.04215111,  1.26582   ,  0.51282889],
       [-0.04215111,  0.18871289, -0.32745867, -0.12082844],
       [ 1.26582   , -0.32745867,  3.09550267,  1.286972  ],
       [ 0.51282889, -0.12082844,  1.286972  ,  0.57713289]])

In [33]:
np.cov(X.T, ddof=0)

array([[ 0.68112222, -0.04215111,  1.26582   ,  0.51282889],
       [-0.04215111,  0.18871289, -0.32745867, -0.12082844],
       [ 1.26582   , -0.32745867,  3.09550267,  1.286972  ],
       [ 0.51282889, -0.12082844,  1.286972  ,  0.57713289]])

# 7.6 조건부기댓값과 예측 문제

노트 작성