# 7.2 기댓값과 확률변수의 변환

### 연습문제 7.2.3

In [ ]:
75

### 연습문제 7.2.4

In [ ]:
노트에 작성

### 연습문제 7.2.5

In [ ]:
노트에 작성

### 연습문제 7.2.6

In [ ]:
표본평균처럼 (편향)표본분산도 확률적인 데이터다. 실현된 표본들을 대상으로 평균에서 얼마나 떨어져있는지를 계산하기 때문이다.
s^2 = 1/n ∑(xi-mean(x))^2

# 7.3 분산과 표준편차

### 연습문제 7.3.1

1. 주사위와 동전을 각각 던졌을 때, 주사위가 3이 나오고 동전은 앞면이 나올 확률
2. 담배를 하루에 몇개비 피우는지와 30년내 폐암 발생확률

### 연습문제 7.3.2

1.

In [2]:
data = np.random.randint(1,10,100)
data

array([8, 1, 9, 4, 3, 1, 3, 2, 6, 9, 6, 2, 8, 1, 1, 4, 2, 4, 5, 5, 6, 6,
       5, 4, 5, 8, 5, 8, 6, 8, 4, 4, 2, 4, 7, 6, 6, 2, 5, 5, 5, 8, 2, 4,
       6, 7, 8, 6, 6, 9, 6, 6, 3, 1, 1, 9, 3, 7, 1, 1, 9, 5, 1, 2, 5, 8,
       2, 8, 6, 5, 5, 8, 6, 9, 1, 1, 1, 6, 8, 2, 9, 7, 3, 1, 8, 4, 6, 3,
       8, 6, 3, 8, 2, 5, 5, 8, 5, 5, 2, 8])

2.

In [3]:
data2 = np.random.randint(1,10,100)
data2

array([4, 3, 3, 2, 9, 3, 5, 9, 9, 4, 7, 8, 2, 6, 5, 8, 9, 2, 9, 4, 5, 1,
       5, 4, 7, 9, 3, 8, 5, 1, 5, 7, 4, 2, 7, 7, 6, 4, 3, 2, 2, 1, 1, 7,
       2, 9, 4, 9, 7, 4, 1, 9, 4, 8, 8, 7, 9, 9, 4, 6, 2, 2, 9, 2, 8, 9,
       6, 3, 2, 3, 7, 4, 4, 9, 5, 3, 7, 6, 4, 4, 2, 2, 1, 4, 1, 6, 3, 7,
       5, 8, 9, 8, 6, 8, 6, 8, 8, 4, 6, 6])

3.

In [5]:
data3 = data + data2
data3

array([12,  4, 12,  6, 12,  4,  8, 11, 15, 13, 13, 10, 10,  7,  6, 12, 11,
        6, 14,  9, 11,  7, 10,  8, 12, 17,  8, 16, 11,  9,  9, 11,  6,  6,
       14, 13, 12,  6,  8,  7,  7,  9,  3, 11,  8, 16, 12, 15, 13, 13,  7,
       15,  7,  9,  9, 16, 12, 16,  5,  7, 11,  7, 10,  4, 13, 17,  8, 11,
        8,  8, 12, 12, 10, 18,  6,  4,  8, 12, 12,  6, 11,  9,  4,  5,  9,
       10,  9, 10, 13, 14, 12, 16,  8, 13, 11, 16, 13,  9,  8, 14])

4.

In [6]:
data_var = np.var(data)
data2_var = np.var(data2)
data3_var = np.var(data3)
data3_var, data_var+ data2_var

(11.9011, 13.007499999999997)

### 연습문제 7.3.3

In [20]:
np.random.seed(0)

x = np.random.normal(size = (100, 50))

x_means = x.mean(axis = 0)

std_xbar = x_means.std()

std_x1 = x[:, 0].std()

std_x1 / std_xbar

9.168983486145807

In [21]:
x_means

array([-0.23860905, -0.02963682,  0.07990919,  0.04965999, -0.10760923,
        0.00931268, -0.08689131, -0.19181566,  0.06943874,  0.09526339,
       -0.09168282,  0.15573291, -0.08256611, -0.19621611, -0.19704871,
       -0.13009662,  0.07711461, -0.09356113, -0.04433717,  0.10112414,
       -0.07018187, -0.09094521, -0.04110922, -0.10128457, -0.04342622,
        0.06231968,  0.08157414,  0.15719825,  0.09395275,  0.13941486,
       -0.07384888,  0.12343539, -0.17910471, -0.07575625, -0.11112913,
       -0.22227549, -0.0952297 , -0.06399927,  0.03699184, -0.0049545 ,
        0.00645924,  0.08366015,  0.17717533,  0.07869636,  0.10283144,
        0.13096031,  0.11156187,  0.03299648, -0.11327075, -0.01649956])