# 5.2 제한조건이 있는 최적화 문제

### 등식 제한조건이 있는 최적화 문제

#### 라그랑주 승수법

제한조건 등식에 λ라는 새로운 변수를 곱해서 더한 함수를 목적함수로 하여 최적화함

제한조건이 m개라면 x1, x2, ... xn, λ1, λ2, ... λm 이라는 n+m 개의 변수와 연립방정식이 생긴다.

### 사이파이를 사용하여 등식 제한조건이 있는 최적화 문제 계산하기

사이파이 optimize 서브패키지의 fmin_slsqp()

**fmin_slsqp(func_objective, x0, eqcons = [func_constraint1, func_constraint2])**

인수: 목적함수, 초깃값, 제한조건 함수의 리스트

### 연습문제 5.2.

In [6]:
def e521(x):
    return -np.log(x[0]) + -np.log(x[1])

def eq_constraint521(x):
    return x[0] + x[1] -1

sp.optimize.fmin_slsqp(e521, np.array([1,1]), eqcons = [eq_constraint521])

Optimization terminated successfully    (Exit mode 0)
            Current function value: 1.3862943611198901
            Iterations: 2
            Function evaluations: 6
            Gradient evaluations: 2


array([0.5, 0.5])

In [7]:
def e522(x):
    return x[0] + x[1]

def eq_constraint522(x):
    return x[0]**2 + x[1]**2 -1

sp.optimize.fmin_slsqp(e522, np.array([1,1]), eqcons = [eq_constraint522])

Optimization terminated successfully    (Exit mode 0)
            Current function value: 1.4142135623747087
            Iterations: 5
            Function evaluations: 15
            Gradient evaluations: 5


array([0.70710678, 0.70710678])

### 라그랑주 승수의 의미

등식 제한조건 gi에 따라 해가 달라진다면 λi != 0

### 부등식 제한조건이 있는 최적화 문제

부등식이 gj(x) >= 0 형태인 경우 양변에 -1룰 곱해서 부등호의 방향을 바꾼다.

목적함수: h(x,λ) = f(x) + ∑λjgj(x)

이 때 **KKT** 조건이 만족되어야 한다.

1. 모든 독립변수 x1, x2, ... xn에 대한 미분값이 0이다. ∂h(x,λ) / ∂xi = 0
2. 모든 라그랑주 승수 λ1, λ2, ... , λn과 제한조건 부등식(λ에 대한 미분값)의 곱이 0이다. λj * ∂h(x,λ) / ∂λj = λj * gj = 0
3. 라그랑주 승수는 음수가 아니어야 한다. λj >= 0

첫 번째 조건에서, 변수 x가 아닌 **라그랑주 승수 λ에 대한 미분은 0이 아니어도 된다.**

두 번째 조건을 통해, 라그랑주 승수 λ에 대한 미분값이 0이거나 **라그랑주 승수 λ값 자체가 0이어도 된다**는 것을 알 수 있다.

세 번째 조건은 KKT 조건이 실제로 부등식 제한조건이 있는 최적화 문제와 같은 문제임을 보장하는 조건이다.

부등식 제한조건이 있는 최적화 문제에서 제한조건은 다음 두 경우 중 하나이다.

1. 최적화 결과에 전혀 영향을 주지 않는 **쓸모없는** 제한조건
2. 최적화 결과에 영향을 주는 **등식** 제한 조건

### 연습문제 5.2.3

2, 3

### 사이파이를 이용하여 부등식 제한조건이 있는 최적화 문제 계산하기

fmin_slsqp의 인수로 ieqcons 사용

**fmin_slsqp(func_objective, x0, ieqcons=[func_constraint1, func_constraint2])**

* 단 ieqcons 인수에 들어가는 부등호의 부호는 0 또는 양수임 g >= 0

In [11]:
def f2(x):
    return np.sqrt((x[0] - 4) ** 2 + (x[1] - 2) ** 2)

# 제한 조건 상수
k = 1
def ieq_constraint(x):
    return np.atleast_1d(k - np.sum(np.abs(x)))

sp.optimize.fmin_slsqp(f2, np.array([0, 0]), ieqcons = [ieq_constraint])

Optimization terminated successfully    (Exit mode 0)
            Current function value: 3.605551280732028
            Iterations: 11
            Function evaluations: 66
            Gradient evaluations: 11


array([9.99999981e-01, 1.89941792e-08])

### 연습문제 5.2.4

In [15]:
def f2(x):
    return np.sqrt((x[0] - 4) ** 2 + (x[1] - 2) ** 2)

# 제한 조건 상수

def ieq_constraint(k):
    return lambda x: np.atleast_1d(k - np.sum(np.abs(x)))
opt = []
k_range = np.linspace(0.1,10,100)
for k in k_range:
    opt += [
        sp.optimize.fmin_slsqp(
        f2, np.array([0, 0]), ieqcons = [ieq_constraint(k)], iprint = 0)
    ]

print(opt)

[array([9.99983654e-02, 1.63456102e-06]), array([1.99998457e-01, 1.54315231e-06]), array([2.99999770e-01, 2.29926611e-07]), array([3.99998929e-01, 1.07067885e-06]), array([4.99999937e-01, 6.34692395e-08]), array([5.99999256e-01, 7.43758148e-07]), array([6.99999453e-01, 5.47035342e-07]), array([7.99996737e-01, 3.26306021e-06]), array([8.99996068e-01, 3.93188638e-06]), array([9.99999981e-01, 1.89941792e-08]), array([1.09999747e+00, 2.53125152e-06]), array([1.19999702e+00, 2.97798576e-06]), array([1.29999828e+00, 1.71518317e-06]), array([1.39998962e+00, 1.03831667e-05]), array([1.49999387e+00, 6.13491897e-06]), array([1.59999230e+00, 7.69787823e-06]), array([1.69999189e+00, 8.11353019e-06]), array([1.79998452e+00, 1.54831185e-05]), array([1.89996414e+00, 3.58578938e-05]), array([1.9978564, 0.0021436]), array([2.04996867, 0.05003133]), array([2.0999624, 0.1000376]), array([2.14995881, 0.15004119]), array([2.19995764, 0.20004236]), array([2.24995824, 0.25004176]), array([2.29996022, 0.30003

### 5.3 선형계획법 문제와 이차계획법 문제

### 선형게획법 문제

방정식이나 부등식 제한 조건을 가지는 선형 모형의 값을 최소화하는 문제

목적함수: **arg min_x cT@x**

등식제한 조건: **A@x = b**(기본형), A@x <= b(정규형)

부등식 제한조건: **x >= 0**

#### 예제

목적함수

 -3*x1 - 5* x2

제한 조건

-x1 <= -100    

-x2 <= 100

x1 + 2*x2<= 500

4*x1+ 5*x2 <= 9800

x1 >=0, x2 >= 0

이후 정규형 선형계획법 문제로 표현하여 풀이

### 사이파이를 이용한 선형계획법 문제 계산

scipy.optimize 패키지의 linprog() 명령 사용

**linprog(c, A, b)**

* c: 목적함수의 계수 벡터
* A: 등식 제한 조건의 계수 행렬
* B: 등식 제한 조건의 상수 벡터

In [21]:
import scipy.optimize

A = np.array([[-1, 0], [0, -1], [1, 2], [4, 5]])
b = np.array([-100, -100, 500, 9800])
c = np.array([-3, -5])

result = sp.optimize.linprog(c, A, b)
result

     con: array([], dtype=float64)
     fun: -1399.999994807386
 message: 'Optimization terminated successfully.'
     nit: 6
   slack: array([1.99999991e+02, 4.19920389e-06, 3.31136675e-07, 8.10000001e+03])
  status: 0
 success: True
       x: array([299.99999127, 100.0000042 ])

### CVXPY를 이용한 선형계획법 문제 계산 (PuLP도 있음)

In [24]:
import cvxpy as cp

# 변수의 정의
a = cp.Variable() # A의 생산량
b = cp.Variable() # B의 생산량

# 조건의 정의
constraint = [
    a >= 100,
    b >= 100,
    a + 2 * b <= 500,
    4 * a + 5 * b <= 9000
]

#문제의 정의
obj = cp.Maximize(3 * a + 5 * b)
prob = cp.Problem(obj, constraint)

# 계산
prob.solve()

# 결과
print("상태:", prob.status)
print('최적값:', a.value, b.value)

상태: optimal
최적값: 299.9999992351282 100.0000004995861


### 이차 계획법 문제

방정식이나 부등식 제한 조건을 가지는 일반화된 이차형식의 값을 최소화하는 문제(QP 문제)

목적함수: 1/2 * x.T @ Q @ x + c.T @ x

등식제한 조건: **A@x = b**(기본형), A@x <= b(정규형)

부등식 제한조건: **x >= 0**

#### 예제

arg min_x x1 ** 2 + x2 ** 2

x1 + x2 - 1 = 0

### CvxOpt를 이용한 이차계획법 문제 계산

* 넘파이의 ndarray 배열을 CvxOpt 전용의 matrix 자료형으로 바꿈
* 정수 자료형을 사용하지 못하므로 항상 부동소수점 실수가 되도록 명시

In [26]:
from cvxopt import matrix, solvers

Q = matrix(np.diag([2.0, 2.0]))
c = matrix(np.array([0.0, 0.0]))
A = matrix(np.array([[1.0, 1.0]]))
b = matrix(np.array([1.0]))

sol = solvers.qp(Q, c, A=A, b=b)
np.array(sol['x'])

array([[0.5],
       [0.5]])

### 연습문제 5.3.1

y1a1+ y2a2 + y3a3 = 0

a1, a2, a3 >= 0

a1 + a2 + a3 -1/2 * (y1y1*a1a1*x1Tx1 + y1y2*a1a2*x1Tx2+ y1y3*a1a3*x1Tx3 + y2y1*a2a1x2Tx1 + y2y2*a2a2*x2Tx2+ y2y3*a2a3*x2Tx3
                    + y3y1*a3a1*x3Tx1 + y3y2*a3a2 * x3Tx2 + y3y3*a3a3*x3Tx3)