### 연습문제 3.4.3

In [6]:
A = np.array([[3, -1], [1, 3], [1, 1]])
U, S, VT = np.linalg.svd(A)

w, V = np.linalg.eig(A @ A.T) 
idx = np.argsort(w **2 )[::-1] # 내림차순 정렬해 재배열
print(w, V)
w = w[idx] 
V = V[:, idx]
print(w, V)

[ 0. 10. 12.] [[ 1.82574186e-01 -8.94427191e-01 -4.08248290e-01]
 [ 3.65148372e-01  4.47213595e-01 -8.16496581e-01]
 [-9.12870929e-01  9.27403771e-16 -4.08248290e-01]]
[12. 10.  0.] [[-4.08248290e-01 -8.94427191e-01  1.82574186e-01]
 [-8.16496581e-01  4.47213595e-01  3.65148372e-01]
 [-4.08248290e-01  9.27403771e-16 -9.12870929e-01]]


### 1차원 근사

2차원 평면 위에 3개의 2차원 벡터 a_1, a_2, a_3이 있을 때, 원점을 지나면서 모든 점들과 가능한 한 가까이 있는 직선을 만들고자 한다.
이때 직선의 방향을 어떻게 해야 할까?

직선의 방향을 나타내는 단위 벡터를 w라 하자.

이 문제는 다음의 수식으로 표현할 수 있다.

**arg max_w (llAwll)^2**

### 1차원 근사의 풀이

예로 든 행렬 A ∈ R^(3x2)를 특잇값분해하여 두 특잇값, 왼쪽/오른쪽 특이벡터를 가진다.

이 때 조건에 맞으면서 목표값을 가장 크게 하는 w는,

w = v1

**즉, 첫 번째 오른쪽 특이벡터 방향으로 하는 것이다.**

이 때 llAwll는 첫 번째 특잇값이 된다.

**llAwll = δ1**

### 일반적인 풀이

n = 3이 아니라 일반적인 경우에는

**llAwll^2 = w.T @ A.T @ A @ w = ∑ (δ_i)^2 * (llV_i.T @ wll)^2**

우리가 풀어야 할 문제는 다음과 같다.

**arg max_w (llAwll)^2 = arg max_w ∑ (δ_i)^2 * (llV_i.T @ wll)^2**

이 값을 가장 크게 하려면 w를 가장 큰 특잇값에 대응하는 오른쪽 고유벡터 v1으로 해야 한다.

### 랭크-1 근사문제

n 개의 m차원 벡터을 1차원으로 투영하여 가장 비슷한 n개의 1차원 벡터를 만드는 문제

즉, 원래 행렬 A에 랭크-1 행렬 ww.T를 곱해서 원래의 행렬 A와 가장 비슷한 행렬 A'을 만드는 문제

arg min_w llA-A'll = **arg min_w llA - A @ w @ w.Tll**

### k 차원 근사

n개의 m차원 벡터를 1차원이 아니라 정규직교인 기저벡터로 이루어진 k차원 벡터공간으로 투영하여<br>
가장 비슷한 n개의 k차원 벡터를 만드는 정규직교 기저벡터를 찾는 문제

* **가장 큰 k개의 특잇값에 대응하는 오른쪽 특이벡터가 기저벡터일 때 가장 값이 커진다.**

### 랭크-k 근사문제

원래 행렬 A에 랭크-k 행렬 WW.T를 곱해서 원래의 행렬 A와 가장 비슷한 행렬 A'를 만드는 문제

* **arg min_(w1,w2...wk) (llA-A @ W @ W.Tll)**