# 고윳값분해

### 고윳값과 고유벡터

정방행렬 A에 대해 다음 식을 만족하는 영벡터가 아닌 벡터 v, 실수 λ를 찾을 수 있다고 가정하자.<br><br>
**Av = λv** <br>
<br>
위 식을 만족하는 실수 λ를 **고윳값**, 벡터 v를 **고유벡터**라고 한다. <br>
고윳값과 고유벡터를 찾는 작업을 **고유분해** 또는 **고윳값 분해**라고 한다.<br> 
<br>
행렬 A의 고유벡터는 행렬 A를 곱해서 변환을 해도 방향이 바뀌지 않는 벡터다.<br>
고윳값은 변환된 벡터와 원래 고유벡터의 크기 비율이다.<br>
<br>

**Av - λv = (A - λ)v = 0**

어떤 벡터 v가 고유벡터가 되면 이 벡터에 실수를 곱한 벡터 cv, 즉 v와 방향이 같은 벡터는 모두 고유벡터가 된다.

**A(cv) = cAv - cλv = λ(cv)**

그래서 보통 고유벡터를 표시할 때는 길이가 1인 단위벡터가 되도록 정규화함
<br>v // llvll

### 연습문제 3.3.1

In [6]:
B = np.array([[2, 3], [2, 1]])
λ1 = 4
λ2 = -1
v1 = np.array([[3], [2]])
v2 = np.array([[-1], [1]])
v1_ = v1 / np.linalg.norm(v1)
v2_ = v2 / np.linalg.norm(v2)
(B @ v1) / λ1 , (B @ v2) / λ2, v1_, v2_

(array([[3.],
        [2.]]),
 array([[-1.],
        [ 1.]]),
 array([[0.83205029],
        [0.5547002 ]]),
 array([[-0.70710678],
        [ 0.70710678]]))

### 특성방정식

행렬 A의 고윳값은 A - λI의 행렬식이 0이 되도록 하는 **특성방정식**의 해를 구하면 된다.<br>
**det(A - λI) = 0** (A - λI의 역행렬이 존재한다면 고윳값 조건을 만족하는 벡터가 항상 영벡터가 됨)<br>
**(A - λI)^-1 (A - λI) = 0 -> v = 0**

특성방정식을 풀었을 때 고윳값의 갯수가 방정식의 차원보다 적을 경우 **중복고윳값**을 가짐

### 고윳값의 개수

중복된 고윳값을 별개로 생각하고 복소수인 고윳값도 고려한다면 n차원 정방행렬의 고윳값은 항상  n개다.

### 고윳값과 대각합/행렬식

어떤 행렬의 고윳값이 λ1, λ2, ... λn 이라고 하면 **모든 고윳값의 곱은 행렬식의 값**과 같고, <br>
**모든 고윳값의 합은 대각합의 값**과 같다.

### 고유벡터의 계산

고윳값을 알면 다음 연립 방정식을 풀어 고유벡터를 구할 수 있다.<br>
**(A - λI)v = 0**

고윳값이 중복되었다고 고유벡터도 항상 중복되는 것은 아님<br>
ex) 2차원 항등행렬 I의 고윳값은 1이라는 중복된 고윳값을 가지지만, <br>
임의의 2차원 벡터는 모두 고유벡터가 된다.

### 넘파이를 사용한 고유분해

**np.linalg.eig(A)**: 고윳값을 벡터 형태로, 고유벡터를 열을 고유벡터로 가지는 행렬 형태로 표현(실수 값 없을 시 복소수 계산)

In [10]:
A = np.array([[1, -2], [2, -3]])
w1, V1 = np.linalg.eig(A)
w1, V1

(array([-0.99999998, -1.00000002]),
 array([[0.70710678, 0.70710678],
        [0.70710678, 0.70710678]]))

In [13]:
B2 = np.array([[2, -3], [2, 1]])
w2, V2 = np.linalg.eig(B)
w2, V2

(array([ 4., -1.]),
 array([[ 0.83205029, -0.70710678],
        [ 0.5547002 ,  0.70710678]]))

In [12]:
C = np.array([[0, -1], [1, 0]])
w3, V3 = np.linalg.eig(C)
w3, V3

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

### 연습문제 3.3.5

In [15]:
E = np.array([[2, 3], [2, 1]])
we, Ve = np.linalg.eig(E)
we, Ve

(array([ 4., -1.]),
 array([[ 0.83205029, -0.70710678],
        [ 0.5547002 ,  0.70710678]]))

In [16]:
F = np.array([[1, 1], [0, 1]])
wf, Vf = np.linalg.eig(F)
wf, Vf

(array([1., 1.]),
 array([[ 1.00000000e+00, -1.00000000e+00],
        [ 0.00000000e+00,  2.22044605e-16]]))

### 대각화

N차원 정방행렬 A가 복소수 고윳값 N개와 이에 대응하는 고유벡터를 가진다는 성질을 이용하면 다음처럼 행렬을 분해할 수 있다.

**고유벡터행렬 V**는 고유벡터를 열벡터로 옆으로 쌓아서 만든 행렬이다.<br>
**고윳값행렬 Λ**은 고윳값을 대각성분으로 가지는 대각행렬이다.<br>
<br>
위와 같이 고유벡터행렬과 고윳값행렬을 정의하면 행렬과 고유벡터행렬의 곱은,<br>
고유벡터행렬과 고윳값행렬의 곱과 같다.<br>
**AV = VΛ**

만약 고유벡터행렬 V의 역행렬이 존재한다면 행렬을  다음처럼 고유벡터행렬과 고윳값행렬의 곱으로 표현할 수 있다.<br>
이를 행렬의 **대각화**라고한다.<br>
**A = VΛΛ^-1**

### 연습문제 3.3.6

In [9]:
A = np.array([[2, 3], [2, 1]])
w1, v1 = np.linalg.eig(A)
v1_inverse =np.linalg.inv(v1)
print(v1, v1_inverse, np.diag(w1))
v1 @ np.diag(w1) @ v1_inverse

[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]] [[ 0.72111026  0.72111026]
 [-0.56568542  0.84852814]] [[ 4.  0.]
 [ 0. -1.]]


array([[2., 3.],
       [2., 1.]])

### 연습문제 3.3.7

In [11]:
B = np.array([[1, 1], [0, 1]])
w2, v2 = np.linalg.eig(B)
v2, np.linalg.matrix_rank(v2)

(array([[ 1.00000000e+00, -1.00000000e+00],
        [ 0.00000000e+00,  2.22044605e-16]]),
 1)

### 대각화가능

고유벡터들이 선형독립일 경우

### 고윳값과 역행렬

대각화 가능한 행렬에 0인 고윳값이 없으면 항상 역행렬이 존재함

### 연습문제 3.3.8

In [19]:
C = np.array([[2, 3], [2, 1]])
w, v = np.linalg.eig(C)
vinv = np.linalg.inv(v)
v @ np.diag(1 / w) @ vinv, np.linalg.inv(C)

(array([[-0.25,  0.75],
        [ 0.5 , -0.5 ]]),
 array([[-0.25,  0.75],
        [ 0.5 , -0.5 ]]))

### 대칭행렬의 고유분해

행렬 A가 실수인 대칭행렬이면 고윳값이 실수이고 고유벡터는 서로직교한다.

만약 고유벡터들이 크기가 1이 되도록 정규화된 상태라면 고유벡터 행렬 V는 정규직교행렬이므로 **전치행렬이 역행렬**이다

**A = V @ Λ @ V.T**